import os,time,sys
from distutils.log import error
alphs = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
numbs = [0,1,2,3,4,5,6,7,8,9]
ko = 1
if ko == 1:
	print('Loading Module |')
	time.sleep(0.2)
	os.system('clear')
	print('Loading Module /')
	time.sleep(0.2)
	os.system('clear')
	print('Loading Module -')
	time.sleep(0.2)
	os.system('clear')
	print("Loading Module \\")
	time.sleep(0.2)
	os.system('clear')
	print('Loading Module |')
	time.sleep(0.2)
	os.system('clear')
	print('Loading Module |')
	time.sleep(0.2)
	os.system('clear')
	print('Loading Module /')
	time.sleep(0.2)
	os.system('clear')
	print('Loading Module -')
	time.sleep(0.2)
	os.system('clear')
	print("\\")
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
	print('/')
	time.sleep(0.2)
	os.system('clear')
	print('-')
	time.sleep(0.2)
	os.system('clear')
	print("\\")
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
	print('/')
	time.sleep(0.2)
	os.system('clear')
	print('-')
	time.sleep(0.2)
	os.system('clear')
	print("\\")
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
	print('/')
	time.sleep(0.2)
	os.system('clear')
	print('-')
	time.sleep(0.2)
	os.system('clear')
	print("\\")
	time.sleep(0.2)
	os.system('clear')
	print('|')
	time.sleep(0.2)
	os.system('clear')
def createnubs(first, second):
	numberf = numbs[first]
	numbers = numbs[second]
	return int(numberf),int(numbers)
def renderText(string, writetime):
	knowit = writetime
	os.system('clear')
	os.system('clear')
	for char in string:
		sys.stdout.write(char)
		sys.stdout.flush()
		time.sleep(writetime)

def deleteText(wait):
	time.sleep(wait)
	os.system('clear')

def PythonRunner():
	for char in 'User@Desktop $ bash -f python.sh':
		sys.stdout.write(char)
		sys.stdout.flush()
		time.sleep(0.1)
	time.sleep(0)
	getboy = input('\nEnter Your Filename: ')
	exec(open(getboy).read())
	